configs:
  pve.yml:
    content: |
      default:
        user: "${PVE_USERNAME}"
        password: "${PVE_PASSWORD}"
        verify_ssl: false

services:  
  pve-exporter:
    container_name: pve-exporter
    image: prompve/prometheus-pve-exporter
    restart: unless-stopped
    networks: ["monitoring"]
    expose: ["9221"]
    configs:
      - source: pve.yml
        target: /etc/prometheus/pve.yml
    command:
      - "--config.file=/etc/prometheus/pve.yml"

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    privileged: true
    devices: ["/dev/kmsg"]
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks: ["monitoring"]
    expose: ["8080"]
    command:
      - "--housekeeping_interval=30s"
      - "--docker_only=true"
      - "--store_container_labels=false"

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    networks: ["monitoring"]
    expose: ["9100"]
    pid: host
    command:
      - "--path.rootfs=/host"
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.udev.data=/host/run/udev/data"
      - "--web.listen-address=0.0.0.0:9100"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    volumes:
      - /:/host:ro,rslave
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro

networks:
  monitoring:
    external: true