services:
  pihole-sync:
    restart: unless-stopped
    image: ghcr.io/lovelaze/nebula-sync:latest
    networks: ["traefik"]
    command:
      - run
    environment:
      - FULL_SYNC=true
      - RUN_GRAVITY=true
      - CRON=*/60 * * * *
      - CLIENT_SKIP_TLS_VERIFICATION=true
      - API_ENABLED=true
      - PRIMARY=${PIHOLE_SYNC_PRIMARY}
      - REPLICAS=${PIHOLE_SYNC_REPLICAS}
networks:
  traefik:
    external: true
