services:
  traefik:
    image: docker.io/traefik:v3.6.11
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
      - TRAEFIK_ENTRYPOINTS_websecure_HTTP_TLS_DOMAINS_0_MAIN=stunthound.com
      - TRAEFIK_ENTRYPOINTS_websecure_HTTP_TLS_DOMAINS_0_SANS=*.stunthound.com
    security_opt:
      - no-new-privileges:true
    volumes:
      - acme:/etc/traefik
      - ./config.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic:/etc/traefik/dynamic
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: ["traefik"]
    ports:
      - name: web
        host_ip: 0.0.0.0
        target: 80
        published: "80"
        protocol: tcp
        app_protocol: http
        mode: host
      - name: websecure
        host_ip: 0.0.0.0
        target: 443
        published: "443"
        protocol: tcp
        app_protocol: https
        mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.stunthound.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_BASIC_AUTH}"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
      - "--certificatesResolvers.le.acme.email=stunthound@gmail.com"
    
networks:
  traefik:
    name: traefik
    driver: bridge

volumes:
  acme: {}