services:
  traefik:
    image: docker.io/traefik:v3.6.11
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - CF_DNS_API_TOKEN=${TRAEFIK_CF_DNS_API_TOKEN}
    security_opt:
      - no-new-privileges:true
    volumes:
      - acme:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks: ["traefik"]
    ports:
      - name: web
        host_ip: 0.0.0.0
        target: 80
        published: "80"
        protocol: tcp
        app_protocol: http
        mode: host
      - name: websecure
        host_ip: 0.0.0.0
        target: 443
        published: "443"
        protocol: tcp
        app_protocol: https
        mode: host
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.stunthound.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_BASIC_AUTH}"
    command:
      - "--configfile="

      # API / Dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"

      # Entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"

      # Docker Provider
      - "--providers.docker=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"

      # Let's Encrypt / Cloudflare DNS
      - "--certificatesresolvers.cloudflare.acme.email=stunthound@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.delaybeforecheck=30"
      - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      
      # Metrics
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.addentrypointslabels=true"
      - "--metrics.prometheus.addserviceslabels=true"
    
networks:
  traefik:
    name: traefik
    driver: bridge

volumes:
  acme: {}